### PR TITLE
Avoid errors on incorrectly defined properties

### LINKED ISSUE #2: Array to string conversion in AssetUsageIndex.php line 202
I got this (thounsands of times) when running `./flow assetusage:updateIndex`:

`Error while processing node "f8971542-ac36-45a3-80e1-2fe30c3c565a": Failed to update usages for node "f8971542-ac36-45a3-80e1-2fe30c3c565a": Failed to extract asset ids from property "imageDesk": Warning: Array to string conversion in /var/www/app/Data/Temporary/Development/SubContextDocker/Cache/Code/Flow_Object_Classes/Wwwision_AssetUsage_AssetUsageIndex.php line 202`

I'll try to find out more…

### PR DESCRIPTION
**Pull request by kdambekalns**
When is not defined correctly (without a type), it is assumed a type of `string`. That leads to the error reported in #2.

This fixes that by checking for the actual type of the `$value`.

Fixes: #2

### CODE REVIEW

File: Classes/AssetUsageIndex.php [hunk 1]
```diff
@@ -198,7 +198,7 @@ public function extractAssetIdsFromPropertyValue(string $type, $value): array
         if ($value instanceof ResourceBasedInterface) {
             return [$this->getAssetId($value)];
         }
-        if ($type === 'string' || is_subclass_of($type, Stringable::class)) {
+        if (is_string($value) || is_subclass_of($type, Stringable::class)) {
```
Comment (bwaidelich) [inline Classes/AssetUsageIndex.php]: I think it makes sense to ignore the `type` definition here, but we should do so in both cases I think:
```suggestion
        if (is_string($value) || $value instanceof Stringable) {
```

btw: we do the same in the Neos 9 built-in [AssetUsageProjection](https://github.com/neos/neos-development-collection/blob/9cd8c4f790955a4d69e7e4baa59a35d5b434e422/Neos.Neos/Classes/AssetUsage/Projection/AssetUsageProjection.php#L204-L207)  (it's a bit simpler because values can only be scalars there)
